baseURL = 'https://drowsyrobotboy.com'
languageCode = 'en-us'
title = 'drowsyrobotboy'
theme = 'kurta'

[params]
    customHeader = "<a href=\"/\" style=\"text-decoration: none; color: #222;\"><h1 style=\"font-size: 2rem;\">DrowsyRobotBoy</h1></a>"
    customCss = "courier-prime.css"
    customIntro = "They call me Drowsy<a href=\"https://www.youtube.com/watch?v=Wbt59pmT26E&amp;ref=drowsyrobotboy.com\">RobotBoy</a> or I <del>make them</del> implore them to."
    customContact = "You can reach out to me at <a href=\"mailto:maruthisharma@live.in\">maruthisharma@live.in</a>"

[params.meta]
    favicon = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'