baseURL = 'https://drowsyrobotboy.com'
languageCode = 'en-us'
title = 'drowsyrobotboy'
theme = 'kurta'

[params]
    customHeader = "<a href=\"/\" style=\"text-decoration: none; color: #222;\"><img src=\"/images/dr-logo.png\" /></a>"
    customCss = "courier-prime.css"
    customCssIndex = 1
    customIntro = "They call me Drowsy<a href=\"https://www.youtube.com/watch?v=Wbt59pmT26E&amp;ref=drowsyrobotboy.com\">RobotBoy</a> or I <del>make them</del> implore them to."
    customContact = "You can reach out to me at <a href=\"mailto:maruthisharma@live.in\">maruthisharma@live.in</a>"

[params.meta]
    favicon = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.highlight]
    noClasses = false     # Use CSS classes instead of inline styles
    style = "monokailight"      # GitHub-style syntax highlighting
    guessSyntax = true    # Detect language if nothing is specified
  [markup.goldmark.renderer]
    unsafe = true