baseURL = 'https://drowsyrobotboy.com'
languageCode = 'en-us'
title = 'drowsyrobotboy | Maruthi Sharma Panchagnula'
theme = 'kurta'

[params.meta]
    favicon = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
