baseURL = 'https://maruthisharma.com'
languageCode = 'en-us'
title = 'Maruthi Sharma Panchagnula'
theme = 'kurta'

[params]
    customHeader = "<a href=\"/\" style=\"text-decoration: none; color: #222;\"><h1 style=\"font-size: 2rem;\">Maruthi Sharma Panchagnula</h1></a>"
    customCss = "maruthi.css"
    customIntro = "<h1>Hi, I am Maruthi</h1>"
    customContact = "You can reach out to me at <a href=\"mailto:msharma@securdi.com\">msharma@securdi.com</a>"

[params.meta]
    favicon = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
