baseURL = 'https://maruthisharma.com'
languageCode = 'en-us'
title = 'Maruthi Sharma Panchagnula'
theme = 'kurta'

[params]
    customHeader = """
    <a class=\"rb-ms-header\" href=\".\">
      <h1 style=\"font-size: 2.2rem;\"> Maruthi Sharma Panchagnula </h1>
    </a>
    """
    defaultFontCss = "ovo.css"
    defaultFontCssIndex = 0
    defaultColorCss = "light.css"
    defaultColorCssIndex = 0
    defaultSyntaxCss = "monokai-light.css"
    defaultSyntaxCssIndex = 0
    customIntro = ""
    customContact = "You can reach out to me at <a href=\"mailto:msharma@securdi.com\">msharma@securdi.com</a>"

[params.meta]
    favicon = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.highlight]
    noClasses = false     # Use CSS classes instead of inline styles
    style = "monokailight"      # GitHub-style syntax highlighting
    guessSyntax = true    # Detect language if nothing is specified
  [markup.goldmark.renderer]
    unsafe = true