[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Posts'
pageRef = 'posts'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = 'projects'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
