[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Posts'
pageRef = 'posts'
weight = 10

[[menus.main]]
name = 'Tech'
pageRef = 'categories/tech'
weight = 11
parent = 'Posts'

[[menus.main]]
name = 'Design'
pageRef = 'categories/design'
weight = 12
parent = 'Posts'

[[menus.main]]
name = 'Music'
pageRef = 'categories/music'
weight = 13
parent = 'Posts'

[[menus.main]]
name = 'Fonts'
url = '#'
weight = 20
[menus.main.params]
  onclick = 'rotateFontCSS()'

[[menus.main]]
name = 'Ovo'
url = '#'
weight = 21
parent = 'Fonts'
[menus.main.params]
  onclick = 'setFontCSS("0")'
  fontClass = 'rb-serif'

[[menus.main]]
name = 'Courier Prime'
url = '#'
weight = 22
parent = 'Fonts'
[menus.main.params]
  onclick = 'setFontCSS("1")'
  fontClass = 'rb-monospace'

[[menus.main]]
name = 'Helvetica Neue'
url = '#'
weight = 23
parent = 'Fonts'
[menus.main.params]
  onclick = 'setFontCSS("2")'
  fontClass = 'rb-sans-serif'

[[menus.main]]
name = 'Colors'
url = '#'
weight = 30
[menus.main.params]
  onclick = 'rotateColorCSS()'

[[menus.main]]
name = 'Light'
url = '#'
weight = 31
parent = 'Colors'
[menus.main.params]
  onclick = 'setColorCSS("0")'

[[menus.main]]
name = 'Dark'
url = '#'
weight = 32
parent = 'Colors'
[menus.main.params]
  onclick = 'setColorCSS("1")'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
