baseURL = 'https://drowsyrobotboy.com'
languageCode = 'en-US'
title = 'DrowsyRobotBoy'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'About'
url = 'https://maruthisharma.com'
weight = 10
[menus.main.params]
  target = "_blank"

[[menus.main]]
name = 'Tech'
pageRef = '/categories/tech'
weight = 20

[[menus.main]]
name = 'Design'
pageRef = '/categories/design'
weight = 30

[[menus.main]]
name = 'Music'
pageRef = '/categories/music'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
